metainfo:
    gender: 'male'
    data_dir : /media/AI/Common/Recon3D/v2a/data/parkinglot
    subject: "parkinglot"
    start_frame: 0
    end_frame: 42
    camera_pos_path: /media/AI/liam/v2a/zara/cam/EOT_ascii_Trans.txt
    camera_rotate_path: /media/AI/liam/v2a/zara/cam/EOT_ascii_Rotate.txt
    start_index: 4200
    
train:
    type: "Video"
    batch_size: 1
    drop_last: False
    shuffle: True
    worker: 8

    num_sample : 512 

valid:
    type: "VideoVal"
    image_id: 0
    batch_size: 1
    drop_last: False
    shuffle: False
    worker: 8

    num_sample : -1
    pixel_per_batch: 2048 

test:
    type: "VideoTest"
    image_id: 0
    batch_size: 1
    drop_last: False
    shuffle: False
    worker: 16

    num_sample : -1
    pixel_per_batch: 2048