metainfo:
    gender: 'female'
    data_dir : data_bbox_2d_init_training_no_pose_1e4/
    subject: "data_bbox_2d_init_training_no_pose_1e4"
    start_frame: 0
    end_frame: 41

train:
    type: "Video"
    batch_size: 1
    drop_last: False
    shuffle: True
    worker: 8

    num_sample : 1024 

valid:
    type: "VideoVal"
    image_id: 0
    batch_size: 1
    drop_last: False
    shuffle: True
    worker: 8

    num_sample : -1
    pixel_per_batch: 2048 

test:
    type: "VideoTest"
    image_id: 0
    batch_size: 1
    drop_last: False
    shuffle: False
    worker: 8

    num_sample : -1
    pixel_per_batch: 2048